### ISSUE TITLE
[Bug] Can't change the Lucky Rollers

### ISSUE THREAD

**Issue by Crasben** [ApexModder/FantasyTable#2]
I tried to change the Lucky Rollers with configured but i couldn't. The text just appears red and the done button doesn't work.

Version of the mod is 3.0.3

**Comment by ApexModder** [comment]
Sounds like you are using some other mod to modify the config in game

The lucky rollers config option expects player UUID's not player names
You can use somewhere like this ([_https://mcuuid.net/_](https://mcuuid.net/)) to obtain UUID's from player names
