### ISSUE TITLE
crash on forge 36.2.31

### ISSUE THREAD

**Issue by jasonisop** [ApexModder/FantasyTable#3]
mod crashes on newer forge versions.
[latest.log](https://github.com/ApexModder/FantasyTable/files/8279464/latest.log)
[crash-2022-03-16_21.10.25-fml.txt](https://github.com/ApexModder/FantasyTable/files/8279475/crash-2022-03-16_21.10.25-fml.txt)

**Comment by ApexModder** [comment]
I am unsure why this error is occuring, seems to only be with version uploaded to curseforge
If i compile a new version the mod loads fine
A new mod version will be publlished ASAP

**Comment by jasonisop** [comment]
Just so you know the previous version also had this issue

**Comment by ApexModder** [comment]
This clearly needs alot more investigating, issue still occurred with a new version
I will investigate this more later when im not busy with other stuff

**Comment by ApexModder** [comment]
@jasonisop I have seemingly fixed the issue in the latest release, it is also highly recommended to update ApexCore & Registrator too as this was a issue with how mods have been built & released (not specific to this one mod)

**Comment by jasonisop** [comment]
this isnt fixed.

**Comment by jasonisop** [comment]
Thanks for the jars but its for a modpack I made, so i will just have to wait for you to get it all sorted out.

**Comment by ApexModder** [comment]
Uploaded the jars to curseforge manually, @jasonisop you can use these versions until a fix has been implemented

[Registrator v1.2.0](https://www.curseforge.com/minecraft/mc-mods/registrator/files/3696768)
[ApexCore v1.3.0](https://www.curseforge.com/minecraft/mc-mods/apexcore/files/3696767)
[FantasyDice v1.2.0](https://www.curseforge.com/minecraft/mc-mods/fantasys-dice/files/3696762)

Sorry for any inconvience

**Comment by jasonisop** [comment]
Thanks that worked.

**Comment by ApexModder** [comment]
Issue should have been resolved with the latest mod releases

## 1.16.5
[Registrator v1.2.1](https://www.curseforge.com/minecraft/mc-mods/registrator/files/3698692)
[ApexCore v1.3.1](https://www.curseforge.com/minecraft/mc-mods/apexcore/files/3698734)
[FantasyDice v1.2.1](https://www.curseforge.com/minecraft/mc-mods/fantasys-dice/files/3698744)

## 1.18.1
[Registrator v3.1.1](https://www.curseforge.com/minecraft/mc-mods/registrator/files/3698799)
[ApexCore v3.1.1](https://www.curseforge.com/minecraft/mc-mods/apexcore/files/3697555)
[FantasyDice v3.2.1](https://www.curseforge.com/minecraft/mc-mods/fantasys-dice/files/3698827)
